spring.application.name=appGrupo1Consumidor
server.port=8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbitmq.queue=Grupo1Queue
app.rabbitmq.exchange=Grupo1Exchange
app.rabbitmq.routingkey=Grupo1Routing
